### ISSUE TITLE
error loading kingdom hearts chain of memories rom

### ISSUE THREAD

**Issue by robotsafari** [Kermalis/VGMusicStudio#126]
i receive this error after trying to open kingdom hearts chain of memories

---------------------------
Error Loading GBA ROM (MP2K)
---------------------------
Error Details:

Error parsing "MP2K.yaml"
Game code "B8CE_00" is missing.
   at Kermalis.VGMusicStudio.Core.GBA.MP2K.Config..ctor(Byte[] rom)
   at Kermalis.VGMusicStudio.Core.Engine..ctor(EngineType type, Object playerArg)
   at Kermalis.VGMusicStudio.UI.MainForm.OpenMP2K(Object sender, EventArgs e)
---------------------------

**Comment by Kermalis** [comment]
It seems that this game doesn't use MP2K, so this tool can't open it
